apiVersion: v1
name: oncall-postinstall-setup
version: 1.10.1
tillerVersion: ">=2.7.2"
description: Helm chart for deploying an istio controlplane
keywords:
  - istio
  - operator
sources:
  - https://github.com/istio/istio/tree/master/operator
engine: gotpl
icon: https://istio.io/latest/favicons/android-192x192.png
