apiVersion: v1
kind: Service
metadata:
  labels:
    name: oncall-web
  name: oncall-web
  namespace: oncall
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: oncall-web