apiVersion: v1
kind: Service
metadata:
  labels:
    name: mysql
  name: mysql
  namespace: oncall
spec:
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  selector:
    app: oncall-mysql