apiVersion: apps/v1
kind: Deployment
metadata: 
  name: oncall-web-deployment
  labels:
    app: oncall-web
  namespace: oncall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oncall-web
  template:
    metadata:
      labels:
        app: oncall-web
    spec:
      containers:
      - name: oncall-web
        image: hcaleb/oncall:firstPush
        imagePullPolicy: IfNotPresent
        env:
        - name: DOCKER_DB_BOOTSTRAP
          value: '1'
        # volumeMounts:
        #   - mountPath: /home/oncall/config
        #     name: config-vol
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "1000Mi"
            cpu: "500m"
        volumeMounts:
          - mountPath: /home/oncall/config/
            name: oncall-configmap-volume
      volumes:
        - name: oncall-configmap-volume
          configMap:
            name: oncall-configmap
      # imagePullSecrets:
      # - name: change to your secret
      # volumes:
      #   - name: config-vol
      #     hostPath:
      #       path: //c/Users
      #       type: Directory
