apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: oncall
spec:
  storageClassName: manual # Remove this line when switching to azure
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi