apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  namespace: oncall
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath: # Change to azure disk
    path: "/mnt/data"
