apiVersion: apps/v1
kind: Deployment
metadata: 
  name: oncall-web-deployment
  labels:
    app: oncall-web
  namespace: oncall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oncall-web
  template:
    metadata:
      labels:
        app: oncall-web
    spec:
      containers:
      - name: oncall-web
        image: hcaleb/oncall:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: DOCKER_DB_BOOTSTRAP
          value: '1'
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: config-secret
              key: CLIENT_SECRET
        - name: EMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: config-secret
              key: email_password
        - name: SESSION_ENCRYPT_KEY
          valueFrom:
            secretKeyRef:
              name: config-secret
              key: session_encrypt_key
        - name: SESSION_SIGN_KEY
          valueFrom:
            secretKeyRef:
              name: config-secret
              key: session_sign_key
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: config-secret
              key: mysql-root-password
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "1000Mi"
            cpu: "500m"
        volumeMounts:
          - mountPath: /home/oncall/config/
            name: oncall-configmap-volume
      volumes:
        - name: oncall-configmap-volume
          configMap:
            name: oncall-configmap
