apiVersion: v1
kind: ConfigMap
metadata:
  name: oncall-configmap
  namespace: oncall
data:
  config.yaml: |
    CLIENT_ID: "5b5b76e0-99ad-4e1e-b62b-c662d0831d06"
    AUTHORITY: "https://login.microsoftonline.com/8ebfe367-26a7-4e40-9484-0939035411f0"
    REDIRECT_URL: "http://localhost/authorize"
    AUDIENCE: "5b5b76e0-99ad-4e1e-b62b-c662d0831d06"
    LOGOUT_URL: "https://login.microsoftonline.com/8ebfe367-26a7-4e40-9484-0939035411f0/oauth2/v2.0/logout"
    server:
      host: 0.0.0.0
      port: 8080
    debug: True
    oncall_host: http://localhost
    metrics: dummy
    db:
      conn:
        kwargs:
          scheme: mysql+pymysql
          user: root
          host: mysql.oncall.svc
          port: 3306
          database: oncall
          charset: utf8
          echo: True
        str: "%(scheme)s://%(user)s:%(password)s@%(host)s/%(database)s?charset=%(charset)s"
      kwargs:
        pool_recycle: 3600
    auth:
      debug: False
      module: 'oncall.auth.modules.debug'
    notifier:
      skipsend: False
    healthcheck_path: /tmp/status
    messengers:
      - type: email_messenger
        application: oncall
        user: 'beckertestoncall@gmail.com'
        server: 'smtp.gmail.com'

      # - type: dummy
      #   application: oncall
      #   iris_api_key: magic

    # allow_origins_list:
    #   - http://www.example.com

    supported_timezones:
      - 'US/Eastern'
      - 'US/Pacific'
      - 'US/Central'
      - 'US/Mountain'
      - 'US/Alaska'
      - 'US/Hawaii'
      - 'Asia/Kolkata'
      - 'Asia/Shanghai'
      - 'UTC'

    index_content_setting:
      #footer: |
      #  <ul>
      #    <li>Oncall © LinkedIn 2020</li>
      #    <li>Feedback</li>
      #    <li><a href="http://oncall.tools" target="_blank">About</a></li>
      #  </ul>
      missing_number_note: 'No number'

    notifications:
      default_roles:
        - "primary"
        - "backup"
        # - "primary-afterHours"
        #- "backup-afterHours"
        - "manager"
      default_times:
        - 86400
        - 604800
      default_modes:
        - "email"

    reminder:
      activated: True
      polling_interval: 360
      default_timezone: 'US/Eastern'

    user_validator:
      activated: True
      subject: 'Warning: Missing phone number in Oncall'
      body: 'You are scheduled for an on-call shift in the future, but have no phone number recorded. Please update your information in Oncall.'

    header_color: '#0078d4'
    


